### ISSUE TITLE
Docs for this.

### ISSUE THREAD

**Issue by HyperSkys** [microsoft/azure-devops-rust-api#3]
Can you provide some documentation on how to use this API?

**Comment by johnbatty** [comment]
See:
- The [README.md](https://github.com/microsoft/azure-devops-rust-api/blob/main/azure_devops_rust_api/README.md) in this repo
- The [examples](https://github.com/microsoft/azure-devops-rust-api/tree/main/azure_devops_rust_api/examples) in this repo (the README explains how to run them)
- The [docs.rs documentation](https://docs.rs/azure_devops_rust_api/latest/azure_devops_rust_api/)
  - There were some problems with the autogeneration of these, but I have just fixed that
 
There is more to be done, but hopefully this should help you get started.  Let me know if you have specific questions.
