### ISSUE TITLE
git::commits::get_changes(...) response parsing fails

### ISSUE THREAD

**Issue by johnbatty** [microsoft/azure-devops-rust-api#31]
Reported by @myadav27.
Querying git commit changes fails, as the server response does not match the spec definition.

Example code:
```rust
    let commit_changes = git_client
        .commits_client()
        .get_changes(&organization, &commit_id, &repository_name, &project)
        .into_future()
        .await?;
```

Error:
```
Error: invalid type: map, expected a string at line 1 column 503
```

The response from the server looks like this:
```json
{
  "changeCounts": {
    "Edit": 1
  },
  "changes": [
    {
      "item": {
        "objectId": "3434a1c33eb40b708cfcebf8e8a5dd17036b1417",
        "originalObjectId": "6c2fe8905129cbfa99faad55f66662132770ef5b",
        "gitObjectType": "blob",
        "commitId": "203c42d1211b1e430d8c69478516b0874cb560e9",
        "path": "/VARIABLES",
        "url": "https://dev.azure.com/<redacted>"
      },
      "changeType": "edit"
    }
  ]
}
```

The autogenerated code is expecting `GitCommitChanges`:
```rust
pub struct GitCommitChanges {
    pub change_counts: Option<ChangeCountDictionary>,
    pub changes: Vec<GitChange>,
}

pub struct ChangeCountDictionary {}  // !!! < This is clearly wrong!

pub struct GitChange {
    #[serde(flatten)]
    pub change: Change,
    pub change_id: Option<i32>,
    pub new_content_template: Option<GitTemplate>,
    pub original_path: Option<String>,
}

pub struct Change {
    pub change_type: Option<change::ChangeType>,
    pub item: Option<String>,   // !!! < This is what is failing to parse - expects a string but the JSON has a map
    pub new_content: Option<ItemContent>,
    pub source_server_item: Option<String>,
    pub url: Option<String>,
}
```

So there appear to be two issues
 - `ChangeCountDictionary` is an empty struct
 - `Change::item` should be a struct rather than a String

In the spec, `ChangeCountDictionary` is defined as this:
```json
    "ChangeCountDictionary": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int32"
          }
        }
      ],
      "properties": {}
    },
```
Looks like the `allOf`/`additionalProperties` is not being handled by the autorust code generator.

`Change.item` is defined as this:
```json
        "item": {
          "description": "Current version.",
          "type": "string",
          "format": "T"
        },
```
The `"format": "T"` here is unusual, and I can't find a definition of this in the OpenAPI reference.
Probably need to use the `vsts-api-patcher` to fix up this definition to replace the `type: string` with a reference to a struct.

**Comment by cataggar** [comment]
Why is `additionalProperties` inside an `allOf`?  Right now, `additionalProperties` usually just maps to a `serde_json::Value`. https://github.com/Azure/azure-sdk-for-rust/issues/579

**Comment by cataggar** [comment]
I workaround would be to set it to a `serde_json::Value` in a `autorust.toml` using 
https://github.com/Azure/azure-sdk-for-rust/blob/0f96ff42a6c8d335feddab6a23521b71fc383d11/services/autorust/codegen/src/autorust_toml.rs#L94-L96

**Comment by cataggar** [comment]
Two examples here:
https://github.com/Azure/azure-sdk-for-rust/search?l=TOML&q=invalid_type

**Comment by johnbatty** [comment]
@cataggar Thanks very much for the suggestions.  However, I ended up fixing via my spec patcher so that all my patching is in one place (plus there was some other tweaking of the structs I wanted to do).
