### ISSUE TITLE
Error in Return Type in Get Items Batch API Call

### ISSUE THREAD

**Issue by haeminlee0630** [microsoft/azure-devops-rust-api#331]
We believe that there is an error with the return type of the [**Get Items Batch**](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/items/get-items-batch?view=azure-devops-rest-7.1&tabs=HTTP) call.

Currently, both the Microsoft Learn documentation and the azure-devops-rust-api expects the return type for the call to return a `Vec<String>` (for rust) or an `array[]` (for C#). 

We believe that this is an error, because when invoking the `.into_body()` method implemented for the **Get Items Batch** call, we get the "failed to deserialize" response with the additional context that "invalid type: map, expected a sequence at line 1 column 0".

Moreover, similar API calls like [**Get Item**](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/items/get?view=azure-devops-rest-7.1&tabs=HTTP) have a more sophisticated return type. In this case, **Get Item** expects a GitItem object. 

Currently we are looking to custom deserialize as a workaround but do _let us know if this this something we could update in the patching layer for the Rust SDK_. Happy to answer any questions as well! :)

**Comment by johnbatty** [comment]
I've published a new release 0.15.2 with a fix for this, plus a new example [`git_items_get_items_batch`](https://github.com/microsoft/azure-devops-rust-api/blob/main/azure_devops_rust_api/examples/git_items_get_items_batch.rs).

Give this a go and let me know whether it works for you.  I wouldn't be surprised if there are some other followon issues.
