### ISSUE TITLE
Code search: Not apparent how to specify search repository and branch

### ISSUE THREAD

**Issue by suttonbradley** [microsoft/azure-devops-rust-api#469]
Looking at the docs for [`CodeSearchRequest`](https://docs.rs/azure_devops_rust_api/latest/azure_devops_rust_api/search/models/struct.CodeSearchRequest.html) and the nested `EntitySearchRequest` and `EntitySearchRequestBase`, it doesn't appear that there's an option for filtering code search on target repository or branch, besides maybe the `filters` field on `EntitySearchRequestBase`, which is just an undocumented `serde_json::Value`.

Is it possible to get more documentation, if this filtering exists, or to have those features added if not?

**Comment by johnbatty** [comment]
Yeah, unfortunately the format of the `filters` field does not seem to be documented in the Azure DevOps documentation :-(

The only document I could find is this [example code search request](https://learn.microsoft.com/en-us/rest/api/azure/devops/search/code-search-results/fetch-code-search-results?view=azure-devops-rest-7.1&tabs=HTTP#examples), which includes a `filters` value.

I tested specifying a target repository and branch, and got this working.  I have updated the `search_code` example with the code to demonstrate how to do it:
- PR: https://github.com/microsoft/azure-devops-rust-api/pull/472
- [`search_code` example](https://github.com/microsoft/azure-devops-rust-api/blob/main/azure_devops_rust_api/examples/search_code.rs)

I hope this helps!
