### ISSUE TITLE
`azure_devops_rust_api::test::results::Client::update()` stalls indefinitely or fails to deserialize.

### ISSUE THREAD

**Issue by mTsBucy1** [microsoft/azure-devops-rust-api#484]
Sorry, this isn't a very pretty report, I sadly don't have the time to investigate this further right now.

But running this request with a body with an `state` enum value that doesn't exist results in this call not returning at all.
Additionally, the `lastUpdatedBy` field in the response will contain `null` values and this breaks some deserialization.

**Comment by johnbatty** [comment]
On your second point, I see that the example response in the [REST API docs](https://learn.microsoft.com/en-us/rest/api/azure/devops/test/results/update?view=azure-devops-rest-7.1&tabs=HTTP) shows `lastUpdatedBy` with an `id` of `null`:

```json
{
  "count": 2,
  "value": [
    {
      "id": 100000,
      "project": {},
      "testRun": {},
      "lastUpdatedBy": {
        "id": null
      },
      "url": ""
    },
    {
      "id": 100001,
      "project": {},
      "testRun": {},
      "lastUpdatedBy": {
        "id": null
      },
      "url": ""
    }
  ]
}
```

Currently the code expects id to always defined.  I'll fix this to make it an `Option`.

**Comment by johnbatty** [comment]
Fix to make `IdentityRef` `id` optional: https://github.com/microsoft/azure-devops-rust-api/pull/485
